// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIv599bMHgasQFPXV9V41Ug5LOmo9Mq7o',
    appId: '1:293054023217:web:d3f6977ab447e799127710',
    messagingSenderId: '293054023217',
    projectId: 'fir-notworkingwithflutter',
    authDomain: 'fir-notworkingwithflutter.firebaseapp.com',
    storageBucket: 'fir-notworkingwithflutter.appspot.com',
    measurementId: 'G-B57PLCBS2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXfhxIOkACs4T90W7Zab6pweSrAJCq7fs',
    appId: '1:293054023217:android:4723d893a417970f127710',
    messagingSenderId: '293054023217',
    projectId: 'fir-notworkingwithflutter',
    storageBucket: 'fir-notworkingwithflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr_nu8uqVmCOlj_Gq4j-o1QFHr790v3VY',
    appId: '1:293054023217:ios:4727c170bd4d152e127710',
    messagingSenderId: '293054023217',
    projectId: 'fir-notworkingwithflutter',
    storageBucket: 'fir-notworkingwithflutter.appspot.com',
    iosClientId: '293054023217-iv7c9h699uifln89kcap7vqoekvcrj8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasenotworkingproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr_nu8uqVmCOlj_Gq4j-o1QFHr790v3VY',
    appId: '1:293054023217:ios:539233c36011ccee127710',
    messagingSenderId: '293054023217',
    projectId: 'fir-notworkingwithflutter',
    storageBucket: 'fir-notworkingwithflutter.appspot.com',
    iosClientId: '293054023217-qa3nus0h9mi5l2k260fv96ai1s67ufvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasenotworkingproject.RunnerTests',
  );
}
